### ISSUE TITLE
Maintainer selection

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework6G1#1]
we have all 3 group members now and this homework is shorter so i think we should do maintainer and task selection early. Who wants to be maintainer?

**Comment by uarif** [comment]
One of you can be the maintainer, just ask professor, I am fine with that. @JustinJaniszewski

**Comment by uarif** [comment]
And yes, you are correct, we should do it fast.

**Comment by WildJimmy** [comment]
Hi all,

I can be the maintainer, no worries. I'll ask the professor now
