### ISSUE TITLE
Boundaries

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework6G1#11]
So the boundaries and bracket are confusing. Is there anything you can help with?

**Comment by pratibha77118** [comment]
@reshnashrestha I too am confused on it. What is the group number and value of n to be used for task 1?

**Comment by WildJimmy** [comment]
For task 1, I believe the group number refers to the number of your homework group, so Homework6g1 should have boundaries [0,10] for the first function, [0. pi] for the second, and [-1,1] for the third. Homework6g1 should have boundaries [0,20] for the first function, [0. 2pi] for the second, and [-1,1] for the third, and so on

**Comment by reshnashrestha** [comment]
It is helpful thank you @WildJimmy
