### ISSUE TITLE
Number of subintervals

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework6G1#13]
Hi  all,
For using Sympson's and Trapezoidal method we have to define the number of subinterval. For this we define the function as "def simpson(f, a, b, n)" , what is the value of n (number of subintervals ) to be used to calculate and plot the integration here?

**Comment by uarif** [comment]
I am not going to do this part, but I guess, that is the number, if I remember correctly, in the class professor put 1000 right?. I hope you figured it out. If not, you can reopen the issue.
