### ISSUE TITLE
Can I use nan_to_num to define a number that approaches zero, but is not exactly zero?

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework6G1#18]

**Comment by WildJimmy** [comment]
Yep, you can set custom replacements too. A bard inquiry reveals you can do something like this

``` Python
def approach_zero(x):
    return np.nan_to_num(x, nan=np.finfo(x.dtype).eps)
```

Which will replace NaN numbers with a small positive value instead. You can do a similar thing with numbers that go to infinity as well

**Comment by pratibha77118** [comment]
The code is not working for me. I instead changed the value of a to as small as 1e-6 to avoid the zero error.
