### ISSUE TITLE
What License to Use?

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework6G1#19]
Which license should we pick? I am personally partial to the MIT license, but am open to whichever works for us.

**Comment by reshnashrestha** [comment]
We group 3 are using Apache 2.0.

**Comment by JustinJaniszewski** [comment]
MIT license sounds good.

**Comment by AhmedCode99** [comment]
Is a license even required?

**Comment by uarif** [comment]
Its not required for the project, (in terms of points) but it is a good practice, as its technically always required for your code @AhmedCode99. I am closing the issue, I believe it's resolved.

**Comment by WildJimmy** [comment]
If we're in agreement that MIT is good then I will go ahead and add that now

**Comment by uarif** [comment]
I guess, which ever license it is, it doesn't matter, as long it allows it.

**Comment by uarif** [comment]
I guess, which ever license it is, it doesn't matter, as long it allows it.
