### ISSUE TITLE
Task distribution

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework6G1#2]
Which task would you guys like to do? I would prefer task 1.

**Comment by uarif** [comment]
I am fine with any of the rest.

**Comment by WildJimmy** [comment]
Hi All,

Shoot, I missed this and opened another issue. Justin if you would like task 1 that is fine by me, I will do task 2 instead (disregard my last issue on this). I'm working now so I will do 2 and make the library if that's okay with you @uarif

**Comment by uarif** [comment]
@WildJimmy , yes go ahead, I will do task 3.

**Comment by WildJimmy** [comment]
Sounds good, I'll close this issue now that tasks are decided
