### ISSUE TITLE
Do we need a folder for a python library with a single file?

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework6G1#20]
Online sources (such as https://packaging.python.org/en/latest/tutorials/packaging-projects/) tell me that when creating a python library, you need to create a folder with the python files you wish to include and an __init__.py file. However, for a single file this leads to the slightly redundant behavior I noted in this issue https://github.com/ubsuny/23-Homework6G1/issues/17.

My point is, do we need to do the whole folder setup, or are we able to just use a single file in this case?

**Comment by uarif** [comment]
Bot ways its fine, you used folder, so its fine.
