### ISSUE TITLE
Singularity resolve

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework6G1#28]
Although I handled the singularity at x=0 for the functions: exp(-1\x)[return np.where(x != 0, np.exp(-1/x), 0)] and cos(1/x) [return np.where(x !=0, np.cos(1/x),0)]
 I am getting the warning
"RuntimeWarning: divide by zero encountered in divide  
How can I resolve this issue? Your response will be appreciated.

**Comment by AhmedCode99** [comment]
This is a possible way of dealing with a singularity: (https://github.com/ubsuny/23-Homework6G2/issues/47)

**Comment by tirthbha** [comment]
@AhmedCode99 Thanks!
