### ISSUE TITLE
How to compare the accuracies for task 1?

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework6G1#32]
In task 1 it is said to compare the accuracies (how many digits are correct) and efficiencies (how many steps does it take to reach a given accuracy). How are we supposed to take the accuracy value? Should we take adaptive trapezoid method as reference or any approximate value of true integral to compare the accuracy?

**Comment by JustinJaniszewski** [comment]
maybe you could take an actual integral function from numpy or something to compare. For accuracy value maybe something like...
 | actual_value - approx_value |  / actual value 
 above is a simple error calculation but it may work here.
