### ISSUE TITLE
Generating calculus.py 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework6G1#33]
Hi @WildJimmy 
Do we need to include all the functions from Task 1 and Task 2 in **calculus.py**?

**Comment by reshnashrestha** [comment]
Yes its clearly mentioned in the homework task.
generate a library `calculus.py` with functions / methods needed for Task 1 and 2.

**Comment by Pranjal-Srivastava-2023** [comment]
Yes all the functions need to be included.

**Comment by JustinJaniszewski** [comment]
reshna and Pranjal have resolved this so I'm closing the issue
