### ISSUE TITLE
Task 3

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework6G1#34]
Hi folks,
Could you let me know if you decided who will complete task 3? I have some queries regarding this.

**Comment by uarif** [comment]
I will do task 3. But I haven't started yet,

**Comment by uarif** [comment]
I hope your queries were resolved after asking the instructor today, right?

**Comment by uarif** [comment]
Anyway, I am happy to keep in touch for further discussions on the topic. @Mosaddeq107

**Comment by reshnashrestha** [comment]
@uarif Is there any progress on your task? Which numpy functions are you considering to compare with the comphys ones?

**Comment by reshnashrestha** [comment]
I have completed my task in group3 if you guys need any help I am happy to help.

**Comment by uarif** [comment]
> @uarif Is there any progress on your task? Which numpy functions are you considering to compare with the comphys ones?

I have considered the first two integrations and compared it with numpy built in.

**Comment by uarif** [comment]
> I have completed my task in group3 if you guys need any help I am happy to help.

Thank you for offering your help
