### ISSUE TITLE
do we need to use boundary conditions in task 2 given in task 1?

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework6G1#36]

**Comment by reshnashrestha** [comment]
I believe we have to.
https://github.com/ubsuny/CompPhys/blob/main/Calculus/rootfinding.ipynb

**Comment by uarif** [comment]
Thanks for the answer @reshnashrestha, I will close this issue, and if anyone of you needed to say anything else, please reopen it.
