### ISSUE TITLE
Task1 Plots

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework6G1#37]
![plots_task1](https://github.com/ubsuny/23-Homework6G1/assets/143649367/49046a88-2b95-4f08-bca7-0c9063779a7a)
Hope these graphs make sense.
In the last plot, constant=1/2, as our group number is 2.

**Comment by reshnashrestha** [comment]
What about the accuracies and efficiencies?

**Comment by tirthbha** [comment]
@reshnashrestha Please go through the link:  https://github.com/ubsuny/23-Homework6G4/pull/37
Hope it will answer your query.

**Comment by uarif** [comment]
I hope its resolved. I am going to close it. Feel free to reopen if anything is needed.
