### ISSUE TITLE
Writing documentation clarified by Dr. Tim 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework6G1#38]
I hope it will clear up your confusion. 

<img width="959" alt="Screenshot 2023-11-20 at 12 15 40 AM" src="https://github.com/ubsuny/23-Homework6G1/assets/66480280/d6589d8b-b5da-4aea-9694-1e93075a9027">

**Comment by WildJimmy** [comment]
That makes sense, thanks!
