### ISSUE TITLE
Root finding method

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework6G1#41]
Which algorithms have you used to find roots?

**Comment by uarif** [comment]
You found any answer for your question?

**Comment by Pranjal-Srivastava-2023** [comment]
@sharmistharanit you can use any two from calculus.py in comphys repository.

**Comment by JustinJaniszewski** [comment]
I believe Pranjal resolved this issue. In our group we have personally used root_secant and root_simple.
