### ISSUE TITLE
How to use import calculus.py in google drive? 

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework6G1#42]
![image](https://github.com/ubsuny/23-Homework6G1/assets/143819849/f6a4c632-7fcc-49ad-b632-c9b56707abb3)
How could I use an import statement like this with our calculus.py file inside of Google Colab?

**Comment by uarif** [comment]
I guess, you first have to keep that file in there or you can first run it there and the import otherwise it will not recognize it, if I am not wrong.

**Comment by JustinJaniszewski** [comment]
I think I understand thank you

**Comment by JustinJaniszewski** [comment]
uploading the file into google colab worked

**Comment by uarif** [comment]
Nice, happy that it worked.
