### ISSUE TITLE
Our documentation will be separate for each task right? 

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework6G1#44]

**Comment by uarif** [comment]
I guess it doesn't matter, Either one master documentation (Where all the members can add their part) or individual, but I guess one documentation makes more sense.

**Comment by reshnashrestha** [comment]
@sharmistharanit Its more like explaining our individual task As mentioned by prof. I have provided the link to that issue:
https://github.com/ubsuny/23-Homework6G3/issues/10

**Comment by uarif** [comment]
Okay, thanx for the explanation

**Comment by uarif** [comment]
I will close this issue, it seems it's resolved.
