### ISSUE TITLE
How I dealt with singularities

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework6G1#45]
In order to avoid dividing by zero, I used the following:

    def f(x):
    # Replace zero values in x with a small positive value to avoid division by zero
    x_safe = np.where(x == 0, np.finfo(float).eps, x)
    return np.exp(-1 / x_safe)

It works perfectly. Feel free to use it.

**Comment by reshnashrestha** [comment]
Thank you for sharing your work. I will try this.

**Comment by uarif** [comment]
Thank you for sharing @AhmedCode99
