### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework6G1#51]
How is task two coming up? @JustinJaniszewski

**Comment by JustinJaniszewski** [comment]
I am supposed to do task 1. Unless I missed an issue about it or something? @WildJimmy is doing Task 2

**Comment by WildJimmy** [comment]
@uarif @JustinJaniszewski Yep, I am doing/did task 2 (root finding). Still haven't worked out that final error with tanh though so I'm looking at that

**Comment by JustinJaniszewski** [comment]
Sounds good. I will uploading the rest of task 1 shortly
