### ISSUE TITLE
Setting up progress in milestone.. 

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework6G1#54]
How can I set up my progress in the milestone? Or it takes it automatically?

**Comment by Pranjal-Srivastava-2023** [comment]
Creating issues in the milestone automatically sets a progress bar.

**Comment by uarif** [comment]
I don't know, in my case it does not work I guess. It's still at 0%

**Comment by uarif** [comment]
But thank you for your response, though. I think it will show progress once my merge req. is accepted.

**Comment by uarif** [comment]
Closing the issue.

**Comment by JustinJaniszewski** [comment]
Not sure if this issue was resolved, so I will mention that the progress bar goes up when issues assigned are closed.

**Comment by JustinJaniszewski** [comment]
For example if you make a new milestone and add a random issue to it, it will be at zero percent still. When that issue is resolved, the progress bar will go up.

**Comment by Pranjal-Srivastava-2023** [comment]
> Not sure if this issue was resolved, so I will mention that the progress bar goes up when issues assigned are closed.

Yes, when the issues in the milestone are closed, the progress bar goes up.
