### ISSUE TITLE
Problem in uploading file from google collab.

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework6G1#61]
![image](https://github.com/ubsuny/23-Homework6G1/assets/143756553/57687f55-270f-4ca3-ba7e-1a0a99d3c452)
Hi, when I uploaded the file from google collab, it appears like this. The figure is overlapping with the code. How can I resolve it?

**Comment by poojashresthacode** [comment]
@WildJimmy @JustinJaniszewski any solution will be highly appreciated.

**Comment by uarif** [comment]
I have never experienced such things but why don't you just keep .py file rather that ipyn?

**Comment by JustinJaniszewski** [comment]
if the file is from a github repository you may just be able to import it

**Comment by JustinJaniszewski** [comment]
oh sorry, i misunderstood the problem. looking at your repository, the file appears fine to me.

**Comment by poojashresthacode** [comment]
I somehow managed to solve the problem, now it's fine. Thankyou all for your effort.
________________________________

**Comment by JustinJaniszewski** [comment]
Glad to hear it.

**Comment by uarif** [comment]
I was here to see if its resolved. Do you care if you share how was it resolved, just for future?

**Comment by JustinJaniszewski** [comment]
I agree, I would like to know the solution
