### ISSUE TITLE
 Bracket]0, pi]

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework6G1#7]
]0, pi].
I have seen this type of bracket in task 1. I think this is open interval. The reason why open interval notation is not written as (0, pi) is because this notation would be ambiguous. The parentheses could be interpreted as either open interval notation or as a function call. To avoid this ambiguity, the notation ]0, pi] is used to explicitly indicate that the interval is open.

I am not sure but correct me guys if I am wrong

**Comment by uarif** [comment]
I believe this was discussed in the class, and I hope it's resolved now, if not, you can reopen it.
