### ISSUE TITLE
HW6 documentation

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework6G1#8]
So the task assignment does not include the documentation part. Do we have to do that? If yes, Whose role could be it?

**Comment by Mosaddeq107** [comment]
To my assumption, since Dr Tim (@laserlab) didn't mention it, we don't need to include that.

**Comment by reshnashrestha** [comment]
@Mosaddeq107 yeah but then prof had replied that we have to summarize our results in each section. Now it’s like we have to individually document for each task so it will be individual.

**Comment by reshnashrestha** [comment]
https://github.com/ubsuny/23-Homework6G3/issues/10

Check this out
