### ISSUE TITLE
requirements file

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework6G1#80]
I know we have had a file like this for the past few homeworks, but I am still unsure what the purpose of it is. Can someone explain?

**Comment by uarif** [comment]
It is helpful for linting and stuff, there you can specify it. It is for the dependencies, versions etc.

**Comment by JustinJaniszewski** [comment]
Oh okay, thank you.

**Comment by uarif** [comment]
You are welcome.
