### ISSUE TITLE
Unexplainable indent error?

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework6G1#87]
While looking at the root finding algorithms to see if they'll play nice with tanh, I started getting this error 

"runcell(0, 'C:/Users/gotta/Documents/calculus/untitled0.py')
  File "C:\Users\gotta\Documents\calculus\calculus.py", line 94
    iterations.append([x, f0])
                              ^
IndentationError: unindent does not match any outer indentation level"

But my code in that file looks like this

![image](https://github.com/ubsuny/23-Homework6G1/assets/94491866/3535abf2-c444-482e-87e8-dde81e92c9e0)
I have no idea what could be causing this, and I've restarted the kernel and everything to make sure it has been imported as in the image above. Any ideas? If not no worries

**Comment by WildJimmy** [comment]
Also ignore the `print("wormy")` statement at the top there, that was just there for some testing purposes

**Comment by JustinJaniszewski** [comment]
hmm, have your tried removing all indents (in that area) and then using TAB to put them back. Somtimes theres like a mixture of spaces where the program has a hardtime for some reason.

**Comment by WildJimmy** [comment]
Yeah, I just restarted the kernal again and it works, I have no idea why....

**Comment by JustinJaniszewski** [comment]
Glad to hear it
